import { gitHubProvider, googleProvider } from "./providers";
import firebaseAdapter from "./firebaseAdapter";

export const authOptions = {
  adapter: firebaseAdapter, // firebase adapter config in firebaseAdapter.ts file
  providers: [googleProvider, gitHubProvider], // all providers in providers folder
  secret: process.env.NEXT_AUTH_SECRET, // this command can be generated by command "openssl rand -base64 32"
};
